<?php

$singular_name = '{{singular_name}}';
$plural_name   = '{{plural_name}}';
$identifier    = 'wp2-studio-' . strtolower($singular_name);

return [
    'name' => $plural_name,
    'alternateName' => $singular_name,
    'identifier' => $identifier,
    'description' => '',
    'additionalType' => '',
    'about' => '',
    'abstract' => '',
    'discussionUrl' => '',
    'documentation' => '',
    'keywords' => [],
    'maintainer' => '',
    'sponsor' => '',
    'thumbnailUrl' => '',
    'usageInfo' => '',
    'version' => '',
    'video' => '',
    'disambiguatingDescription' => '',
    'downloadUrl' => '',
    'installUrl' => '',
    'codeRepository' => '',
    'location' => '',
    'category' => '',
    'brand' => '',
    'color' => '',
    'featureList' => [],
    'image' => '',
    'businessFunction' => [],
    'potentialAction' => [],
    'sameAs' => [],
    'subjectOf' => [],
    'url' => '',
    'post_types' => [
        [
            'post_type' => sanitize_key($singular_name),
            'args' => [
                'labels' => [
                    'name' => $plural_name,
                    'singular_name' => $singular_name,
                    'add_new' => 'Add New',
                    'add_new_item' => 'Add New ' . $singular_name,
                    'edit_item' => 'Edit ' . $singular_name,
                    'new_item' => 'New ' . $singular_name,
                    'view_item' => 'View ' . $singular_name,
                    'view_items' => 'View ' . $plural_name,
                    'search_items' => 'Search ' . $plural_name,
                    'not_found' => 'No ' . $plural_name . ' found',
                    'not_found_in_trash' => 'No ' . $plural_name . ' found in Trash',
                    'all_items' => 'All ' . $plural_name,
                    'archives' => $singular_name . ' Archives',
                    'attributes' => $singular_name . ' Attributes',
                    'insert_into_item' => 'Insert into ' . $singular_name,
                    'uploaded_to_this_item' => 'Uploaded to this ' . $singular_name,
                    'filter_items_list' => 'Filter ' . $plural_name . ' list',
                    'items_list_navigation' => $plural_name . ' list navigation',
                    'items_list' => $plural_name . ' list',
                    'item_published' => $singular_name . ' published.',
                ],
                'public' => false,
                'hierarchical' => false,
                'publicly_queryable' => false,
                'menu_icon' => 'dashicons-admin-generic',
                'supports' => [
                    'title',
                    'editor',
                    'thumbnail',
                    'custom-fields',
                    'revisions',
                    'author',
                    'autosave',
                    'page-attributes',
                    'post-formats',
                    'comments',
                    'trackbacks',
                    'excerpt',
                ],
                'has_archive' => strtolower($plural_name),
                'rewrite' => [
                    'slug' => strtolower($singular_name),
                ],
                'show_in_rest' => true,
                'rest_base' => strtolower($singular_name),
            ],
        ]
    ],
    'sha256' => '',
    'isRelatedTo' => [],
];
